blog/urls.py
from django.urls import path
from .import views
from .views import other_page
from .views import by_rubric, register
#from .views import RegisterDoneView
#from .views import user_activate
from django.contrib.auth import views as auth_views
from .views import profile
from .views import ChangeUserinfoView, STR_PasswordChangeView
from .views import profile_post_add
from .views import profile_post_change, profile_post_delete
from main.views import index

urlpatterns = [
#    path('logout/', auth_views.LoginView.as_view(), name='logout') ,
    path('profile/', profile, name='profile'),
    path('profile/add/', profile_post_add, name='profile_post_add'),
    path('profile/change/<int:pk>/', profile_post_change, name='profile_post_change'),
    path('profile/delete/<int:pk>/', profile_post_delete, name='profile_post_delete'),
#    path('register/activate/<str:sign>/', user_activate, name='register_activate'),
#    path('register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('login/', auth_views.LoginView.as_view(), name='login'), 
    path('logout/', auth_views.LogoutView.as_view(), name='logout'), 
    path('register/', register, name='register'),
    path('login/', views.user_login, name='login'),
    path('', views.post_list, name='post_list'),
    path('index', index, name='index'),
    #path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>', other_page, name='other'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('password/change/', STR_PasswordChangeView.as_view(), name='password_change'),
    path('profile/change/', ChangeUserinfoView.as_view(), name='change_user_info'),

]

main/urls.py
from django.urls import path
from .views import index
from .views import document
from .views import st_detail, std_detail, profile_st_delete,profile_std_delete
from .views import profile_st_change, profile_std_change
from .views import login, profile_st_add, profile_std_add
from .views import st_edit, profile_st, profile_std, std_edit
from .views import by_rubric_st, by_rubric_std
app_name = 'main'

urlpatterns = [
path('accounts/login', login, name='login'),

path('profile_st/delete/<int:pk>/', profile_st_delete, name='profile_st_delete'),
path('profile_std/delete/<int:pk>/', profile_std_delete, name='profile_std_delete'),
path('profile_st/change/<int:pk>/', profile_st_change, name='profile_st_change'),
path('profile_std/change/<int:pk>/', profile_std_change, name='profile_std_change'),
path('profile_st/add/', profile_st_add, name='profile_st_add'),
path('profile_std/add/', profile_std_add, name='profile_std_add'),
path('<int:pk>/st_detail/', st_detail, name='st_detail'),
path('<int:pk>/std_detail/', std_detail, name='std_detail'),
path('profile_st/', profile_st, name='profile_st'),
path('profile_std/', profile_std, name='profile_std'),
path('<int:pk>/by_rubric_st/', by_rubric_st, name='by_rubric_st'),
path('<int:pk>/', by_rubric_std, name='by_rubric_std'),
path('accounts/document', document, name='document'),
path('<int:pk>/st_edit/', st_edit, name='st_edit'),
path('std_edit/<int:pk>/', std_edit, name='std_edit'),
path('', index, name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
#from django.urls import include, path  
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='')),
    path ('', include ('main.urls', namespace='')),
    #path('captcha/', include('captcha.urls')),
]
if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.МEDIA_URL, document_root = settings.МEDIA_ROOT)
    #import debug_toolbar
    urlpatterns = [
        #path('__debug__/',  include( debug_toolbar.urls)), 
          # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ]  +  urlpatterns

main/forms.py
from django import forms
from .models import St, StDocument
from .models import Comment
from .models import StSuperRubric, StSubRubric, StDSuperRubric, StDSubRubric

class StSubRubricForm(forms.ModelForm):
    stsuper_rubric = forms.ModelChoiceField(queryset = StSuperRubric.objects.all(), empty_label=None, 
                                          label = 'Надрубрика', required = False)
    class Meta:
        model = StSubRubric
        fields = '__all__'
        
class StDSubRubricForm(forms.ModelForm):
    stdsuper_rubric = forms.ModelChoiceField(queryset = StDSuperRubric.objects.all(), empty_label=None, 
                                          label = 'Надрубрика', required = False)
    class Meta:
        model = StDSubRubric
        fields = '__all__'
        
class SearchForm(forms.Form):
    keyword = forms.CharField(required = False, max_length = 20, label = '')
    
class StForm(forms.ModelForm):
    class Meta:
        model = St
        fields = '__all__'
        widgets = {'author':forms.HiddenInput}
#AIFormSet = inlineformset_factory(St, fields='__all__')

class StDocumentForm(forms.ModelForm):
    class Meta:
        model = StDocument
        fields = '__all__'
        widgets = {'author':forms.HiddenInput}
#AIFormSet = inlineformset_factory(St, fields='__all__')
class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'st':forms.HiddenInput}

main/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from .models import StDocument, StSubRubric, StDSubRubric
from .forms import StForm, StDocumentForm 
from django.utils import timezone
from django.shortcuts import redirect

@login_required
def profile_std_change(request, pk):
    std = get_object_or_404(StDocument, pk=pk)
    if request.method == 'POST':
        form = StDocumentForm(request.POST, request.FILES, instance=std)
        if form.is_valid():
            std = form.save()
            messages.add_message(request, messages.SUCCESS, 'Проект исправлен')
            return redirect('main:profile_std')
    else:
        form = StDocumentForm(instance=std)
        context = {'form':form}
        return render(request, 'profile_std_change.html', context) 
@login_required
def profile_std_delete(request, pk):
    std = get_object_or_404(StDocument, pk=pk)
    if request.method == 'POST':
        std.delete()
        messages.add_message(request, messages.SUCCESS, 'Проект будет удален')
        return redirect ('main:profile_std')
    else:
        context = {'std':std}
        return render(request, 'profile_std_delete.html', context)


@login_required
def profile_st_change(request, pk):
    st = get_object_or_404(St, pk=pk)
    if request.method == 'POST':
        form = StForm(request.POST, request.FILES, instance=st)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Проект исправлен')
            return redirect('main:profile_st')
    else:
        form = StForm(instance=st)
        context = {'form':form}
        return render(request, 'profile_st_change.html', context) 
@login_required
def profile_st_delete(request, pk):
    st = get_object_or_404(St, pk=pk)
    if request.method == 'POST':
        st.delete()
        messages.add_message(request, messages.SUCCESS, 'Проект будет удален')
        return redirect ('main:profile_st')
    else:
        context = {'st':st}
        return render(request, 'profile_st_delete.html', context)


@login_required
def profile_std_add(request):
    if request.method == 'POST':
        form = StDocumentForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
#            formset = AIFormSet(request.POST, request.FILES, instance=std)
#            if formset.is_valid():
#             formset. save ()
            messages.add_message(request, messages.SUCCESS, 'Документ добавлен')
            return redirect('main/profile_std')
    else:
        form = StDocumentForm(initial={'author':request.user.pk})
#        formset = AIFormSet()
        context = {'form':form}
        return render(request, 'main/profile_std_add.html', context)


@login_required
def profile_st_add(request):
    if request.method == 'POST':
        form = StForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
#            formset = AIFormSet(request.POST, request.FILES, instance=st)
#            if formset.is_valid():
#             formset. save ()
            messages.add_message(request, messages.SUCCESS, 'Проект добавлен')
            return redirect('profile_st')
    else:
        form = StForm(initial={'author':request.user.pk})
#        formset = AIFormSet()
        context = {'form':form}
        return render(request, 'main/profile_st_add.html', context)

@login_required
def profile_std(request):
    stds = StDocument.objects.filter(author=request.user.pk)
    context = {'stds': stds}
    return render(request, 'main/profile_std.html', context)

@login_required
def profile_st(request):
    sts = St.objects.filter(author=request.user.pk)
    context = {'sts': sts}
    return render(request, 'main/profile_st.html', context)

def by_rubric_st(request, pk):
    strubric = get_object_or_404(StSubRubric, pk=pk)
    sts = St.objects.filter(is_active=True, strubric=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        sts = sts.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(sts, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'strubric':strubric, 'page':page, 'sts':page.object_list, 'form':form}
    return render(request, 'main/by_rubric_st.html', context)

def by_rubric_std(request, pk):
    stdrubric = get_object_or_404(StDSubRubric, pk=pk)
    stds = StDocument.objects.filter(is_active=True, stdrubric=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        stds = stds.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(stds, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'stdrubric':stdrubric, 'page':page, 'sts':page.object_list, 'form':form}
    return render(request, 'main/by_rubric_std.html', context)

def document(request):
    documents = StDocument.objects.all()
    return render(request, 'main/document.html', { 'documents':documents })


def login(request):
    return render(request, 'main/login.html')  
  
def index(request):
    sts = St.objects.filter(is_active=True)[:10]
    context = { 'sts': sts }
    return render(request, 'main/index.html', context) 

from django.db.models import Q
from .models import St
from .forms import SearchForm
from django.contrib import messages
    
@login_required
def st_detail(request, pk):
    st = get_object_or_404(St, pk=pk)
    #ais = st.additionalimage_set.all()
    context = {'st': st, 'pk':pk}
    return render(request, 'main/st_detail.html', context)

@login_required
def std_detail(request, pk):
    std = get_object_or_404(StDocument, pk=pk)
    #ais = st.additionalimage_set.all()
    context = {'std': std, 'pk':pk}
    return render(request, 'main/std_detail.html', context)

@login_required
def st_edit(request, pk):
    st = get_object_or_404(St, pk=pk)
    if request.method == "POST":
        form = StForm(request.POST, instance=st)
        if form.is_valid():
            st = form.save(commit=False)
            st.author = request.user
            st.created_at = timezone.now()
            st.save()
            return redirect('main:st_detail', pk=st.pk)
    else:
        form = StForm(instance=st)
    return render(request, 'main/st_edit.html', {'form': form})

def std_edit(request, pk):
    std = get_object_or_404(StDocument, pk=pk)
    if request.method == "POST":
        form = StDocumentForm(request.POST, instance=std)
        if form.is_valid():
            std = form.save(commit=False)
            std.author = request.user
            std.created_at = timezone.now()
            std.save()
            return redirect('main:std_detail', pk=std.pk)
    else:
        form = StDocumentForm(instance=std)
    return render(request, 'main/std_edit.html', {'form': form})

main/templates/main/bad_signature.html
{% extends "layout/basic.html" %}
{% block title %}Ошибка при активации{% endblock %}
{% block content %}
<h2>Активация</h2>
<p>Активация пользователя с таким именем прошда неудачно<p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

main/templates/main/base_doc.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="ru">
	<head>
  <meta http-equiv="Content-Type"
  content="text/html; charset=utf-8">
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
 {% bootstrap_css %}
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
     <link rel="stylesheet" href="{% static 'css/style.css' %}">
      {% bootstrap_javascript jquery='slim' %}
     <link href='https://fonts.googleapis.com/css?family=Open+Sans:700,400,300&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
     <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
     
     <link href='https://fonts.googleapis.com/css?family=Open+Sans:700,400,300&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <title>Блог пожилого ЧПУшника</title>
</head>
	<body>
	   
	<header>	
		<div class="container-fluid">
		<div class="row">
			<nav class="navbar navbar-expand-md navbar-dark  block fixed-top bg-dark text-light" role="navigation>
				<a class="navbar-brand" href="#" role="banner"><H5> СЕКРЕТЫ ЧПУ </H5></a>
				
              		<div class="collapse navbar-collapse" id="navbarsDefault">
					<ul class="navbar-nav ml-auto">
					
					<a class="sr-only sr-only-focusable" href="#content">
						<li class="nav-item"><a class="nav-link root" href="{% url 'post_list' %}">Форумы</a> 
						<li class="nav-item"><a class="nav-link root" href="{% url 'main:document'  %}">Документация</a></li>
                       
                        <li class="nav-item"><a class="nav-link root" href="{% url 'index'  %}">Проекты</a></li>
						<li class="nav-item"><a class="nav-link root" href="{% url 'other' page='about' %}">О сайте</a></li>
					</ul>
					</div>
					
      <ul class="col nav justify-content-end ">
        <li class="nav-item">
          <A class="nav-link" href="{% url 'register' %}">Регистрация</a></li>
           {% if request.user.is_activated %}
            <li class="nav-item dropdown">
              <A class="nav-link dropdown-toggle"
              data-toggle="dropdown" href="#"
              role="button" aria-haspopup="true"
              aria-expanden="False">Профиль </a>
              <div class="dropdown-menu">
                <A class="dropdown-item" href="{% url 'main:profile_std' %}">Moи документы</a>
                  <A class="dropdown-item" href="{% url 'change_user_info' %}">Изменить личные данные</a>
                    <a class="dropdown-item" href="{% url 'password_change' %}">Изменить пароль</a>
                    <div class="dropdown-divider"></div>
                    <A class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
                      <div class="dropdown-divider"></div>
                      <A class="dropdown-item" href="{% url 'profile_post_delete' pk=user.pk %}">Удалить</a>
               </div>
            </li>
                    {% else %}
                    <li class="nav-item"><A class="nav-link"
                      href="{% url 'login' %}">Bxoд</a></li>
                      {% endif %}
        </ul>

 
			</nav>
		 </div>	
		 </div>
	</header>
  <div class="row"><div class="w-100"></div>
                    <nav class="col-md-2 mb-8 nav flex-column border ;"><h1>.   </h1>
                      <A class="nav-link root "
                      {% for stdrubric in stdrubrics %}
                      {% ifchanged stdrubric.stdsuper_rubric.pk %}
                      <span class="nav-link root font-weight-Ьold">
                        {{ stdrubric.stdsuper_rubric.name }}</span>
                        {% else %}
                        "                                                  "
                        {% endifchanged %}
                        <A class="nav-link" href="{% url 'main:by_rubric_std' pk=stdrubric.pk %}">
                          {{ stdrubric.name }}</a>
                          {% endfor %}
                     </nav>   
					
                   
                       <section class="col-md-6 mb-8 nav flex-column border"><h1>.   </h1>
                       <div class="w-100"></div>
                           
                            {% block content %}
                            {% endblock %}
                          </section>
            
                      
        </div>
	</body>
	
	 <footer class="mt-3">
                          <P class="text-right font-italic">&copy; В.А.Стрельников, 2020 г.</p>
                          </footer>

</html>

main/templates/main/by_rubric.html
{% extends "blog/base.html" %}
{% load thumbnail %}
{% load static %}
{% load bootstrap4 %}

{% block title %}{{ rubric }}{% endblock %}

{% block searchform %}
{% endblock %}

{% block content %}
<h2 class="mb-2">{{ rubric }}</h2>
<div class="container-fluid mb-2">
    
</div>
{% if sts %}
<ul class="list-unstyled">
    {% for st in sts %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' rubric_pk=rubric.pk pk=st.pk as url %}
        <a href="{{ url }}{{ all }}">
        {% if st.image %}
        <img class="mr-3" src="{% thumbnail st.image 'default' %}">
        {% else %}
        <img class="mr-3" src="{% static 'main/empty.jpg' %}">
        {% endif %}
        </a>
        <div class="media-body">
          <h3><a href="{{ url }}{{ all }}">{{ st.title }}</a></h3>
          <div>{{ st.content }}</div>
          <p class="text-right font-weight-bold">{{ st.price }}</p>
          <p class="text-right font-italic">{{ st.created_at }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

main/templates/main/by_rubric_std.html
{% extends 'main/base_doc.html' %}

{% load bootstrap4 %}
{% block title %}{{ stdrubric }}{% endblock %}

{% block searchform %}
{% endblock %}

{% block content %}
<h2 class="mb-2">{{ stdrubric }}</h2>
<div class="container-fluid mb-2">
    
</div>
{% if posts %}
<ul class="list-unstyled">
    {% for post in posts %}
    <li class="media my-5 p-3 border">
        {% url 'detail' stdrubric_pk=stdrubric.pk pk=st.pk as url %}
        <a href="{% url 'doc_detail' pk=document.pk %}">
        
        </a>
        <div class="media-body">
          <h3><a href="{% url 'doc_detail' pk=document.pk %}">{{ document.title }}</a></h3>
          <div>{{ post.text }}</div>
          <p class="text-right font-weight-bold">{{ std.price }}</p>
          <p class="text-right font-italic">{{ std.created_date }}</p>
        </div>
        <a href="{% url 'post_detail' pk=post.pk %}">Comments: {{ std.approved_comments.count }}</a>
    </li>
    {% endfor %}
</ul>

{% endif %}
{% endblock %}

main/templates/main/create.html
{% extends "blog/base.html" %}
{% load bootstrap4 %}
{% block title %}Добавление объявления{% endblock %}
{% blосk content %)
<h2>До6авление объявления</h2>
<form method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Добавить">
</form>
{ % endblock % }

main/templates/main/detail.html
{% extends "blog/base.html" %}
{% load bootstrap4 %}
{% block title %}{{ document.title }}-{% endblock %}
{% block content %}
<div class="container-fluid mt-3">
<div class="row">
<h5>{{ st.title }}</h5>
<div class="w-100"></div>
<div class="col">
<P>{{ st.content }}</p>
<p class="font-weight-bold">{{ st.created_at }}</p>

</div>
</div>
{% endblock %}

main/templates/main/doc_rubric.html
{% extends "blog/base.html" %}
{% load thumbnail %}
{% load static %}


{% block title %}{{ rubric }}{% endblock %}

{% block searchform %}
{% endblock %}

{% block content %}
<h2 class="mb-2">{{ rubric }}</h2>
<div class="container-fluid mb-2">
    
</div>
{% if sts %}
<ul class="list-unstyled">
    {% for st in sts %}
    <li class="media my-5 p-3 border">
        {% url 'main:detail' rubric_pk=rubric.pk pk=st.pk as url %}
        <a href="{{ url }}{{ all }}">
        {% if st.image %}
        <img class="mr-3" src="{% thumbnail st.image 'default' %}">
        {% else %}
        <img class="mr-3" src="{% static 'main/empty.jpg' %}">
        {% endif %}
        </a>
        <div class="media-body">
          <h3><a href="{{ url }}{{ all }}">{{ st.title }}</a></h3>
          <div>{{ st.content }}</div>
          <p class="text-right font-weight-bold">{{ st.price }}</p>
          <p class="text-right font-italic">{{ st.created_at }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}

main/templates/main/index.html
{% extends "main/base_pr.html" %}
{% block content %}
{% load bootstrap4 %}
<h2>Последние 10 проектов</h2>
{% if sts %}
<ul class="list-unstyled">
    {% for st in sts %}
<div class="container-fluid mt-3">
    <li class="media my-5 p-3 border">
         <div class="media-body">
          <h5><a href="{% url 'main:st_detail' pk=st.pk %}">{{ st.title }}</a></h5>
          <p class="text-right font-weight-bold">{{ st.price }}</p>
          <p class="text-right font-italic">{{ st.created_at }}</p>
        </div>
    </li>
    {% endfor %}
</ul>
</div>
{% endif %}

{% endblock %}

main/templates/main/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div>

main/templates/main/profile_st.html
{% extends 'main/base_pr.html' %}
{% load bootstrap4 %}
{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<p><a href="{% url 'main:profile_st_add' %}">Добавить проект</a></p>
{% if sts %}
<h3>Ваши проекты</h3>
<ul class="list-unstyled">
    {% for st in sts %}
    <li class="media my-5 p-3 border">
        {% url 'main:profile_st_detail' pk=post.pk as url %}
        <a href="{{ url }}">
        </a>
        <div class="media-body">
            <p>Рубрика: {{ st.rubric }}</p>
            <h3><a href="{{ url }}">{{ st.title }}</a></h3>
            <div>{{ st.content }}</div>
            <p class="text-right font-weight-bold">{{ st.price }}</p>
            <p class="text-right font-italic">{{ st.created_at }}</p>
            <p class="text-right mt-2">
                <a href="{% url 'main:profile_st_change' pk=st.pk %}">Исправить</a>
                <a href="{% url 'main:profile_st_delete' pk=st.pk %}">Удалить</a>
            </p>
        </div>
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

main/templates/main/profile_st_add.html
{% extends 'main/base_pr.html' %}
{% load bootstrap4 %}
{% block title %}Добавление проекта - Профиль пользователя{% endblock %}
{% block content %}
<h2>Добавление проекта</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Добавить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/profile_st_detail.html
{% extends "main/base_pr.html" %}
{% load bootstrap4 %}
{% block title %}{{ st.title }} - Профиль пользователя{% endblock %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        <div class="col">
            <h2>{{ st.title }}</h2>
            <p>{{ st.content }}</p>
            <p class="font-weight-bold">{{ st.price }}</p>
            <p>{{ st.contacts }}</p>
            <p class="text-right font-italic">Проект добавлен {{ st.created_at }}</p>
        </div>
    </div>
</div>
<p><a href="{% url 'profile_st' %}">Назад</a></p>
{% if comments %}
<div class="mt-5">
    {% for comment in comments %}
    <div class="my-2 p-2 border">
        <h5>{{ comment.author }}</h5>
        <p>{{ comment.content }}</p>
        <p class="text-right font-italic">{{ comment.created_at }}</p>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

main/templates/main/profile_std_detail.html
{% extends "main/base_doc.html" %}
{% load bootstrap4 %}
{% block title %}{{ std.title }} - Профиль пользователя{% endblock %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">
        <div class="col">
            <h2>{{ std.title }}</h2>
            <p>{{ std.content }}</p>
            <p class="font-weight-bold">{{ st.price }}</p>
            <p>{{ std.contacts }}</p>
            <p class="text-right font-italic">Документ добавлен {{ std.created_at }}</p>
        </div>
    </div>
</div>
<p><a href="{% url 'main:profile_std' %}">Назад</a></p>
{% if comments %}
<div class="mt-5">
    {% for comment in comments %}
    <div class="my-2 p-2 border">
        <h5>{{ comment.author }}</h5>
        <p>{{ comment.content }}</p>
        <p class="text-right font-italic">{{ comment.created_at }}</p>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

main/templates/main/st_detail.html
{% extends 'main/base_pr.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="post">
       
        {% if user.is_authenticated %}
        <a class="btn btn-outline-primary my-2 " href="{% url 'main:st_edit' pk=st.pk %}">Изменить<span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <h1>{{ st.title }}</h1>
         <div class="date">{{ st.created_at }}
         </div>
        <p>{{ st.context|linebreaksbr }}</p>
    </div>
    
{% endblock %}